import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SocialsContainer from "../components/common/SocialsContainer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid place-items-center grid-cols-2 grid-rows-2 gap-4 min-h-screen ">
        <div className="col-span-2">
          <h1 className="font-bold">
            Here goes the search bar, and snackar filtering 
          </h1>
        </div>
        <div >
          <h1>2nd row will be for nav,search results /jobs</h1> 
        </div>
      </main>

      <footer className={styles.footer}>
        <h4 className="text-sm text-slate-500">Socials:</h4>
        <SocialsContainer />
      </footer>
    </div>
  );
};

export default Home;
